<?php
namespace Util;
class CommonConstant{
    const SELECT_ALL_VALUE = 'ALL';

    const CATEGORY_POSITION_ARTICLE = 'POS_ARTICLE';
    const CATEGORY_SUB_ARTICLE = 'SUB_ARTICLE';
    const CATEGORY_SUB_GAME = 'SUB_GAME';
    const CATEGORY_ARTICLE = 'ARTICLE';
    const CATEGORY_GAME = 'GAME';
    const CATEGORY_ARTICLE_EVENT_CODE = 'EVENT';
    const CATEGORY_ARTICLE_TOPSLIDER_CODE = 'TS';
    const CATEGORY_ARTICLE_TINH_NANG_CODE = 'TN';
    const CATEGORY_ARTICLE_HUONG_DAN_CODE = 'GUIDE';
    const CATEGORY_ARTICLE_HOAT_DONG_CODE = 'HD';
    const CATEGORY_ARTICLE_TNNB_CODE = 'TNNB';
    const CATEGORY_ARTICLE_PLAY_CODE = 'PLAY';
    const CATEGORY_ARTICLE_HEADER_BAR_CODE = 'H_BAR';



    const CATEGORY_SUB_GALLERY = 'SUB_GALLERY';

    const UPLOAD_TYPE_ARTICLE_TOPIC_IMAGE = 'ARTICLE-TOPIC-IMAGE';
    const UPLOAD_TYPE_ARTICLE_THUMB_IMAGE = 'ARTICLE-THUMB-IMAGE';
    const UPLOAD_TYPE_GAME_THUMB_IMAGE = 'GAME-THUMB-IMAGE';
    const UPLOAD_TYPE_GAME_TOPIC_IMAGE = 'GAME-TOPIC-IMAGE';

    const GIFT_CODE_ACTIVE = 1;
    const GIFT_CODE_EXPIRED = 2;
    const GIFT_CODE_FACEBOOK = 'FB';
}